name: Cypress Tests

on: push

jobs:
  cypress:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
